"""Ghanaian languages we do not collect yet.

Source: https://github.com/AfriSpeech/afriso, filtered to living
individual languages spoken in Ghana, minus the four already running.
Someone whose language is here can still sign up; they go on the list
and start receiving words when it opens.

Anything marked ADDED below is not in afriso's Ghana list but is spoken here,
so it must be re-added by hand if this file is ever regenerated.
"""

OTHER_LANGUAGES = [
    ('abr', 'Abron', ['Bron', 'Brong', 'Doma']),
    ('adq', 'Adangbe', ['Adan', 'Adantonwi', 'Agotime']),
    ('ada', 'Adangme', ['Dangme']),
    ('ade', 'Adele', ['Bedere', 'Bidire', 'Gadre']),
    ('aha', 'Ahanta', []),
    ('anf', 'Animere', ['Anyimere', 'Kunda']),
    ('cko', 'Anufo', ['Chakosi', 'Chokosi', 'Chokossi']),
    ('any', 'Anyin', ['Agni', "Agni'", 'Anyi']),
    ('avn', 'Avatime', ['Afatime', 'Avatime, Siya', 'Sia']),
    ('afu', 'Awutu', ['Guang']),
    ('bim', 'Bimoba', ['Moar', 'Moba', 'Moor']),
    ('bib', 'Bissa', ['Bisa']),
    ('kzc', 'Bondoukou Kulango', ['Bonduku Kulango', 'Kolango', 'Koulango']),
    ('nku', 'Bouna Kulango', ['Bouna Koulango', 'Buna Kulango', 'Koulango']),
    ('bwu', 'Buli (Ghana)', ['Builsa', 'Bulea', 'Buli']),
    ('cli', 'Chakali', []),
    ('cll', 'Chala', ['Cala', 'Cãla', 'Tsa']),
    ('cpn', 'Cherepon', ['Chiripon', 'Chiripong', 'Guang']),
    ('ncu', 'Chumburung', ['Chumburu', 'Chumburung (Yeji)', 'Guang']),
    ('mzw', 'Deg', ['Aculo', 'Buro', 'Buru']),
    ('ntr', 'Delo', ['Ntribou', 'Ntribu', 'Ntrubo']),
    ('doy', 'Dompo', ['Dumpo', 'Guang', 'Ndmpo']),
    ('nnu', 'Dwang', ['Dwan', 'Guang', 'Nchumunu']),
    ('fat', 'Fanti', []),
    ('gur', 'Farefare', ['Frafra', 'Gurenne', 'Gurne']),
    ('gpe', 'Ghanaian Pidgin English', ['Pidgin English, Ghanaian']),
    ('acd', 'Gikyode', ['Chode', 'Guang', 'Kyode']),
    ('gjn', 'Gonja', ['Guang', 'Ngbanyito']),
    ('gwx', 'Gua', ['Anum-Boso', 'Guang', 'Gwa']),
    ('hag', 'Hanga', ['Anga']),
    # ADDED: afriso files Hausa under BF, BJ, CM, NE, NG and TD, but it is
    # widely spoken in Ghana, particularly in Zongo communities.
    ('hau', 'Hausa', ['Haoussa', 'Hausawa']),
    ('ahl', 'Igo', ['Achlo', 'Ago', 'Ahlon']),
    ('kpo', 'Ikposo', ['Akposo', 'Akposos', 'Akposso']),
    ('jwi', 'Jwira-Pepesa', ['Pepesa-Jwira']),
    ('kbp', 'Kabiyè', ['Cabrai', 'Cabrais', 'Kab']),
    ('jmr', 'Kamara', ['Mara']),
    ('xkt', 'Kantosi', ['Dagaare-Dioula', 'Dagaari Dioula', 'Dagaari-Jula']),
    ('xsm', 'Kasem', ['Kasena', 'Kasim', 'Kassem']),
    ('xon', 'Konkomba', ['Kom Komba', 'Kpankpam', 'Kpəkpam']),
    ('kma', 'Konni', ['Koma', 'Komung', 'Koni']),
    ('kph', 'Kplang', ['Guang', 'Prang']),
    ('kye', 'Krache', ['Guang', 'Kaakyi', 'Krachi']),
    ('kus', 'Kusaal', ['Koussassé', 'Kusale', 'Kusasi']),
    ('las', 'Lama (Togo)', ['Lama', 'Lamba', 'Losso']),
    ('lar', 'Larteh', ['Gua', 'Guang', 'Late']),
    ('lef', 'Lelemi', ['Buem', 'Lafana', 'Lefana']),
    ('lig', 'Ligbi', ['Banda', 'Dzowo', 'Huela']),
    ('lob', 'Lobi', ['Lobiri', 'Miwa']),
    ('lgq', 'Logba', ['Ghana']),
    ('ffm', 'Maasina Fulfulde', ['Ful (East Maasina), Ful (West Maasina)', 'Fula', 'Fulah-Idiome']),
    ('bfo', 'Malba Birifor', ['Birifo', 'Birifor, Malba', 'Malba-Birifor']),
    ('maw', 'Mampruli', ['Mampelle', 'Mamprule', 'Mamprusi']),
    ('mfq', 'Moba', ['Ben', 'Moa', 'Moab']),
    ('mos', 'Mossi', ['Mole', 'Moore', 'Mooré']),
    ('nfr', 'Nafaanra', ['Banda', 'Dzama', 'Gambo']),
    ('nmz', 'Nawdm', ['Losso', 'Losu', 'Naoudem']),
    ('naw', 'Nawuri', ['Guang']),
    ('nlu', 'Nchumbulu', ['Guang']),
    ('gng', 'Ngangam', ['Dye', 'Gamgan', 'Gangam']),
    ('nkq', 'Nkami', []),
    ('nko', 'Nkonya', []),
    ('dgi', 'Northern Dagara', ['Dagaare', 'Dagaari', 'Dagara']),
    ('bud', 'Ntcham', ['Basaal', 'Basar', 'Basare']),
    ('nyb', 'Nyangbo', ['Nyangbo-Tafi', 'Tutrugbu']),
    ('nzi', 'Nzima', ['Appolo', 'Nzema']),
    ('sig', 'Paasaal', ['Funsile', 'Pasaale', 'Pasaale Sisaala']),
    ('saf', 'Safaliba', ['Safalaba', 'Safalba', 'Safali']),
    ('sfw', 'Sehwi', ['Asahyue', 'Sefwi']),
    ('lip', 'Sekpele', ['Bosele', 'Likpe', 'Mu']),
    ('snw', 'Selee', ['Bale', 'Santrokofi', 'Sele']),
    ('sld', 'Sissala', ['Sisaali', 'Sisala']),
    ('akp', 'Siwu', ['Akpafu', 'Akpafu-Lolobi', 'Lolobi-Akpafu']),
    ('biv', 'Southern Birifor', ['Birifo', 'Birifor, Southern', 'Ghana Birifor']),
    ('dga', 'Southern Dagaare', ['Dagaare', 'Dagaare, Southern', 'Dagaari']),
    ('nnw', 'Southern Nuni', ['Nibulu', 'Nouni', 'Nounouma']),
    ('tcd', 'Tafi', ['Nyangbo-Tafi', 'Tegbo']),
    ('tpm', 'Tampulma', ['Tampele', 'Tamplima', 'Tampole']),
    ('kdh', 'Tem', ['Cotocoli', 'Kotokoli', 'Temba']),
    ('sil', 'Tumulung Sisaala', ['Hissala', 'Isaalung', 'Isala']),
    ('bov', 'Tuwuli', ['Bawuli', 'Bowili', 'Bowiri']),
    ('vag', 'Vagla', ['Kira', 'Konosarola', 'Paxala']),
    ('wlx', 'Wali (Ghana)', ['Ala', 'Ouala', 'Waali']),
    ('wss', 'Wasa', ['Wasaw', 'Wassa']),
    ('ssl', 'Western Sisaala', ['Busillu Sisala', 'Hissala', 'Isala']),
]

OTHER_BY_CODE = {code: (name, alt) for code, name, alt in OTHER_LANGUAGES}
