"""Regenerate shola/languages.py from afriso.

    python3 scripts/build_languages.py afriso/languages.csv afriso/countries.csv

Every living African language afriso knows, minus the ones SHOLA seeds itself.
Extinct, historical and constructed languages are left out: a volunteer cannot
contribute data in a language nobody speaks.

Source: https://github.com/AfriSpeech/afriso (SIL ISO 639-3 + Glottolog,
CC BY 4.0). Regenerate rather than hand-edit - the file is 2,000 rows long and
hand edits will be lost the next time it is rebuilt.
"""
import csv
import sys
from pathlib import Path

# Seeded in config.py with their own keyboards, and stored under two codes that
# predate our using ISO ones. Left out here so they are not listed twice.
SEEDED_ISO = {"twi", "ewe", "gaa", "dag"}

HEADER = '''"""Every African language SHOLA collects, bar the few seeded in config.py.

Generated by scripts/build_languages.py from afriso, which builds on the SIL
ISO 639-3 tables and Glottolog. Do not hand-edit: regenerate.

{count:,} living languages across {countries} countries. Someone whose language
has nothing in it yet still signs up - they are the first speaker, and what they
type becomes the options everyone after them votes on.

Each row is (ISO 639-3 code, name, [alternative names], [country codes]). The
alternative names matter more than they look: a speaker searching for their own
language rarely types the name a standards body chose for it.
"""

OTHER_LANGUAGES = [
'''

FOOTER = ''']

OTHER_BY_CODE = {code: (name, alt, countries)
                 for code, name, alt, countries in OTHER_LANGUAGES}

# So somebody can find their language by typing where it is spoken, which many
# will reach for before its name.
COUNTRY_NAMES = {
'''


def main(src, countries_src=None, dest=Path("shola/languages.py")):
    rows = list(csv.DictReader(open(src, encoding="utf-8")))
    keep = [r for r in rows
            if r["type"] == "living" and r["iso639_3"] not in SEEDED_ISO]
    keep.sort(key=lambda r: r["name"].casefold())

    countries = {c for r in keep for c in r["countries"].split(";") if c}
    out = [HEADER.format(count=len(keep), countries=len(countries))]
    for r in keep:
        alt = [a for a in r["alt_names"].split(";") if a][:6]
        got = [c for c in r["countries"].split(";") if c]
        out.append(f"    ({r['iso639_3']!r}, {r['name']!r}, {alt!r}, {got!r}),\n")
    out.append(FOOTER)
    if countries_src:
        for c in sorted(csv.DictReader(open(countries_src, encoding="utf-8")),
                        key=lambda c: c["name"]):
            out.append(f"    {c['code2']!r}: {c['name']!r},\n")
    out.append("}\n")
    Path(dest).write_text("".join(out), encoding="utf-8")
    print(f"{len(keep):,} languages, {len(countries)} countries -> {dest}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
